# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UImqhwSV.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QSize(1024, 768))
        MainWindow.setMaximumSize(QSize(1024, 768))
        MainWindow.setCursor(QCursor(Qt.ArrowCursor))
        self.OpenDB = QAction(MainWindow)
        self.OpenDB.setObjectName(u"OpenDB")
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        self.ExportDB = QAction(MainWindow)
        self.ExportDB.setObjectName(u"ExportDB")
        self.SaveExcel = QAction(MainWindow)
        self.SaveExcel.setObjectName(u"SaveExcel")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1021, 721))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.AirportSelect = QListView(self.tab)
        self.AirportSelect.setObjectName(u"AirportSelect")
        self.AirportSelect.setGeometry(QRect(10, 30, 101, 91))
        self.AirportSelect.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 221, 16))
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(140, 30, 151, 16))
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(140, 60, 151, 16))
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(140, 90, 54, 12))
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(140, 120, 151, 16))
        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(140, 150, 151, 16))
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(140, 180, 151, 16))
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(140, 210, 151, 16))
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(140, 240, 151, 16))
        self.label_10 = QLabel(self.tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(140, 270, 151, 16))
        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(140, 300, 151, 16))
        self.AirportID = QLineEdit(self.tab)
        self.AirportID.setObjectName(u"AirportID")
        self.AirportID.setGeometry(QRect(290, 30, 113, 20))
        self.AirportName = QLineEdit(self.tab)
        self.AirportName.setObjectName(u"AirportName")
        self.AirportName.setGeometry(QRect(290, 60, 113, 20))
        self.AirportICAO = QLineEdit(self.tab)
        self.AirportICAO.setObjectName(u"AirportICAO")
        self.AirportICAO.setGeometry(QRect(290, 90, 113, 20))
        self.AirportLat = QLineEdit(self.tab)
        self.AirportLat.setObjectName(u"AirportLat")
        self.AirportLat.setGeometry(QRect(290, 120, 113, 20))
        self.AirportLongt = QLineEdit(self.tab)
        self.AirportLongt.setObjectName(u"AirportLongt")
        self.AirportLongt.setGeometry(QRect(290, 150, 113, 20))
        self.AirportElv = QLineEdit(self.tab)
        self.AirportElv.setObjectName(u"AirportElv")
        self.AirportElv.setGeometry(QRect(290, 180, 113, 20))
        self.AirportTA = QLineEdit(self.tab)
        self.AirportTA.setObjectName(u"AirportTA")
        self.AirportTA.setGeometry(QRect(290, 210, 113, 20))
        self.AirportTL = QLineEdit(self.tab)
        self.AirportTL.setObjectName(u"AirportTL")
        self.AirportTL.setGeometry(QRect(290, 240, 113, 20))
        self.AirportSpd = QLineEdit(self.tab)
        self.AirportSpd.setObjectName(u"AirportSpd")
        self.AirportSpd.setGeometry(QRect(290, 270, 113, 20))
        self.AirportSpdH = QLineEdit(self.tab)
        self.AirportSpdH.setObjectName(u"AirportSpdH")
        self.AirportSpdH.setGeometry(QRect(290, 300, 113, 20))
        self.label_24 = QLabel(self.tab)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(140, 330, 151, 16))
        self.AirportAICAO = QLineEdit(self.tab)
        self.AirportAICAO.setObjectName(u"AirportAICAO")
        self.AirportAICAO.setGeometry(QRect(290, 330, 113, 20))
        self.RunwaySelect = QListView(self.tab)
        self.RunwaySelect.setObjectName(u"RunwaySelect")
        self.RunwaySelect.setGeometry(QRect(460, 30, 81, 91))
        self.label_45 = QLabel(self.tab)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(460, 10, 91, 16))
        self.SaveAirport = QPushButton(self.tab)
        self.SaveAirport.setObjectName(u"SaveAirport")
        self.SaveAirport.setGeometry(QRect(10, 130, 101, 41))
        self.SaveRunway = QPushButton(self.tab)
        self.SaveRunway.setObjectName(u"SaveRunway")
        self.SaveRunway.setGeometry(QRect(460, 130, 81, 23))
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(0, 670, 1001, 21))
        self.RunwayID = QLineEdit(self.tab)
        self.RunwayID.setObjectName(u"RunwayID")
        self.RunwayID.setGeometry(QRect(740, 30, 113, 20))
        self.label_14 = QLabel(self.tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(590, 30, 151, 16))
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(590, 60, 151, 16))
        self.RAirportID = QLineEdit(self.tab)
        self.RAirportID.setObjectName(u"RAirportID")
        self.RAirportID.setGeometry(QRect(740, 60, 113, 20))
        self.RIdent = QLineEdit(self.tab)
        self.RIdent.setObjectName(u"RIdent")
        self.RIdent.setGeometry(QRect(740, 90, 113, 20))
        self.label_16 = QLabel(self.tab)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(590, 90, 151, 16))
        self.label_17 = QLabel(self.tab)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(590, 120, 151, 16))
        self.label_18 = QLabel(self.tab)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(590, 150, 151, 16))
        self.RTureHeading = QLineEdit(self.tab)
        self.RTureHeading.setObjectName(u"RTureHeading")
        self.RTureHeading.setGeometry(QRect(740, 120, 113, 20))
        self.RLength = QLineEdit(self.tab)
        self.RLength.setObjectName(u"RLength")
        self.RLength.setGeometry(QRect(740, 150, 113, 20))
        self.RWidth = QLineEdit(self.tab)
        self.RWidth.setObjectName(u"RWidth")
        self.RWidth.setGeometry(QRect(740, 180, 113, 20))
        self.label_51 = QLabel(self.tab)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(590, 180, 151, 16))
        self.label_52 = QLabel(self.tab)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(590, 210, 151, 16))
        self.RSurface = QComboBox(self.tab)
        self.RSurface.setObjectName(u"RSurface")
        self.RSurface.setGeometry(QRect(740, 210, 111, 22))
        self.RLat = QLineEdit(self.tab)
        self.RLat.setObjectName(u"RLat")
        self.RLat.setGeometry(QRect(740, 240, 113, 20))
        self.label_53 = QLabel(self.tab)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(590, 240, 151, 16))
        self.RLongt = QLineEdit(self.tab)
        self.RLongt.setObjectName(u"RLongt")
        self.RLongt.setGeometry(QRect(740, 270, 113, 20))
        self.label_54 = QLabel(self.tab)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(590, 270, 151, 16))
        self.RHeight = QLineEdit(self.tab)
        self.RHeight.setObjectName(u"RHeight")
        self.RHeight.setGeometry(QRect(740, 300, 113, 20))
        self.label_55 = QLabel(self.tab)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(590, 300, 151, 16))
        self.ILSID = QLineEdit(self.tab)
        self.ILSID.setObjectName(u"ILSID")
        self.ILSID.setGeometry(QRect(740, 330, 113, 20))
        self.label_56 = QLabel(self.tab)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(590, 330, 151, 16))
        self.ILSFreq = QLineEdit(self.tab)
        self.ILSFreq.setObjectName(u"ILSFreq")
        self.ILSFreq.setGeometry(QRect(740, 360, 113, 20))
        self.label_57 = QLabel(self.tab)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(590, 360, 151, 16))
        self.label_58 = QLabel(self.tab)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(590, 390, 151, 16))
        self.ILSAngle = QLineEdit(self.tab)
        self.ILSAngle.setObjectName(u"ILSAngle")
        self.ILSAngle.setGeometry(QRect(740, 390, 113, 20))
        self.label_59 = QLabel(self.tab)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(590, 420, 151, 16))
        self.ILSLat = QLineEdit(self.tab)
        self.ILSLat.setObjectName(u"ILSLat")
        self.ILSLat.setGeometry(QRect(740, 420, 113, 20))
        self.ILSLongt = QLineEdit(self.tab)
        self.ILSLongt.setObjectName(u"ILSLongt")
        self.ILSLongt.setGeometry(QRect(740, 450, 113, 20))
        self.label_60 = QLabel(self.tab)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(590, 450, 151, 16))
        self.label_61 = QLabel(self.tab)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(590, 480, 151, 16))
        self.label_62 = QLabel(self.tab)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(590, 510, 151, 16))
        self.ILSIdent = QLineEdit(self.tab)
        self.ILSIdent.setObjectName(u"ILSIdent")
        self.ILSIdent.setGeometry(QRect(740, 510, 113, 20))
        self.label_63 = QLabel(self.tab)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(590, 540, 151, 16))
        self.LocHeading = QLineEdit(self.tab)
        self.LocHeading.setObjectName(u"LocHeading")
        self.LocHeading.setGeometry(QRect(740, 540, 113, 20))
        self.label_64 = QLabel(self.tab)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(590, 570, 151, 16))
        self.ILSTCH = QLineEdit(self.tab)
        self.ILSTCH.setObjectName(u"ILSTCH")
        self.ILSTCH.setGeometry(QRect(740, 570, 113, 20))
        self.label_65 = QLabel(self.tab)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(590, 600, 151, 16))
        self.label_66 = QLabel(self.tab)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(590, 630, 151, 16))
        self.ILSHeight = QLineEdit(self.tab)
        self.ILSHeight.setObjectName(u"ILSHeight")
        self.ILSHeight.setGeometry(QRect(740, 630, 113, 20))
        self.label_12 = QLabel(self.tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 650, 1001, 21))
        self.ILSDME = QCheckBox(self.tab)
        self.ILSDME.setObjectName(u"ILSDME")
        self.ILSDME.setGeometry(QRect(740, 600, 16, 16))
        self.ILSDME.setTristate(False)
        self.ILSCategory = QComboBox(self.tab)
        self.ILSCategory.setObjectName(u"ILSCategory")
        self.ILSCategory.setGeometry(QRect(740, 480, 111, 22))
        self.AirportSearchButton = QPushButton(self.tab)
        self.AirportSearchButton.setObjectName(u"AirportSearchButton")
        self.AirportSearchButton.setGeometry(QRect(10, 320, 91, 31))
        self.AirportSearch = QLineEdit(self.tab)
        self.AirportSearch.setObjectName(u"AirportSearch")
        self.AirportSearch.setGeometry(QRect(10, 290, 91, 20))
        self.SaveILS = QPushButton(self.tab)
        self.SaveILS.setObjectName(u"SaveILS")
        self.SaveILS.setGeometry(QRect(460, 330, 81, 23))
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.WPSearchEdit = QLineEdit(self.tab_3)
        self.WPSearchEdit.setObjectName(u"WPSearchEdit")
        self.WPSearchEdit.setGeometry(QRect(10, 10, 113, 21))
        self.WPSearchButton = QPushButton(self.tab_3)
        self.WPSearchButton.setObjectName(u"WPSearchButton")
        self.WPSearchButton.setGeometry(QRect(130, 7, 101, 26))
        self.WPSearchResult = QListView(self.tab_3)
        self.WPSearchResult.setObjectName(u"WPSearchResult")
        self.WPSearchResult.setGeometry(QRect(10, 40, 111, 121))
        self.label_19 = QLabel(self.tab_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 180, 151, 16))
        self.WPIdent = QLineEdit(self.tab_3)
        self.WPIdent.setObjectName(u"WPIdent")
        self.WPIdent.setGeometry(QRect(170, 180, 113, 21))
        self.WPID = QLineEdit(self.tab_3)
        self.WPID.setObjectName(u"WPID")
        self.WPID.setGeometry(QRect(170, 210, 113, 21))
        self.label_20 = QLabel(self.tab_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 210, 151, 16))
        self.WPCountry = QLineEdit(self.tab_3)
        self.WPCountry.setObjectName(u"WPCountry")
        self.WPCountry.setGeometry(QRect(170, 240, 113, 21))
        self.label_21 = QLabel(self.tab_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 240, 151, 16))
        self.label_22 = QLabel(self.tab_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 270, 151, 16))
        self.WPCollcated = QLineEdit(self.tab_3)
        self.WPCollcated.setObjectName(u"WPCollcated")
        self.WPCollcated.setGeometry(QRect(170, 270, 113, 21))
        self.WPName = QLineEdit(self.tab_3)
        self.WPName.setObjectName(u"WPName")
        self.WPName.setGeometry(QRect(170, 300, 113, 21))
        self.label_28 = QLabel(self.tab_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(20, 300, 151, 16))
        self.WPLat = QLineEdit(self.tab_3)
        self.WPLat.setObjectName(u"WPLat")
        self.WPLat.setGeometry(QRect(170, 330, 113, 21))
        self.WPLongt = QLineEdit(self.tab_3)
        self.WPLongt.setObjectName(u"WPLongt")
        self.WPLongt.setGeometry(QRect(170, 360, 113, 21))
        self.label_29 = QLabel(self.tab_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 330, 151, 16))
        self.label_95 = QLabel(self.tab_3)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(20, 360, 151, 16))
        self.WPNav = QLineEdit(self.tab_3)
        self.WPNav.setObjectName(u"WPNav")
        self.WPNav.setGeometry(QRect(170, 390, 113, 21))
        self.label_96 = QLabel(self.tab_3)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(20, 390, 151, 16))
        self.WPSave = QPushButton(self.tab_3)
        self.WPSave.setObjectName(u"WPSave")
        self.WPSave.setGeometry(QRect(20, 440, 75, 23))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.TMAAPSearch = QLineEdit(self.tab_2)
        self.TMAAPSearch.setObjectName(u"TMAAPSearch")
        self.TMAAPSearch.setGeometry(QRect(10, 10, 113, 20))
        self.TMAAPSearchButton = QPushButton(self.tab_2)
        self.TMAAPSearchButton.setObjectName(u"TMAAPSearchButton")
        self.TMAAPSearchButton.setGeometry(QRect(10, 40, 111, 23))
        self.TMAList = QListView(self.tab_2)
        self.TMAList.setObjectName(u"TMAList")
        self.TMAList.setGeometry(QRect(10, 140, 111, 221))
        self.label_23 = QLabel(self.tab_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 110, 121, 16))
        self.label_25 = QLabel(self.tab_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 80, 131, 16))
        self.LineList = QListView(self.tab_2)
        self.LineList.setObjectName(u"LineList")
        self.LineList.setGeometry(QRect(10, 400, 111, 281))
        self.label_26 = QLabel(self.tab_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 370, 111, 16))
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1024, 23))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
#if QT_CONFIG(shortcut)
        self.label_2.setBuddy(self.AirportID)
        self.label_3.setBuddy(self.AirportName)
        self.label_4.setBuddy(self.AirportICAO)
        self.label_5.setBuddy(self.AirportLat)
        self.label_6.setBuddy(self.AirportLongt)
        self.label_7.setBuddy(self.AirportElv)
        self.label_8.setBuddy(self.AirportTA)
        self.label_9.setBuddy(self.AirportTL)
        self.label_10.setBuddy(self.AirportSpd)
        self.label_11.setBuddy(self.AirportSpdH)
        self.label_24.setBuddy(self.AirportAICAO)
        self.label_14.setBuddy(self.AirportID)
        self.label_15.setBuddy(self.AirportID)
        self.label_16.setBuddy(self.AirportID)
        self.label_17.setBuddy(self.AirportID)
        self.label_18.setBuddy(self.AirportID)
        self.label_51.setBuddy(self.AirportID)
        self.label_52.setBuddy(self.AirportID)
        self.label_53.setBuddy(self.AirportID)
        self.label_54.setBuddy(self.AirportID)
        self.label_55.setBuddy(self.AirportID)
        self.label_56.setBuddy(self.AirportID)
        self.label_57.setBuddy(self.AirportID)
        self.label_58.setBuddy(self.AirportID)
        self.label_59.setBuddy(self.AirportID)
        self.label_60.setBuddy(self.AirportID)
        self.label_61.setBuddy(self.AirportID)
        self.label_62.setBuddy(self.AirportID)
        self.label_63.setBuddy(self.AirportID)
        self.label_64.setBuddy(self.AirportID)
        self.label_65.setBuddy(self.AirportID)
        self.label_66.setBuddy(self.AirportID)
#endif // QT_CONFIG(shortcut)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.OpenDB)
        self.menu.addAction(self.SaveExcel)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Fenix A320 \u5bfc\u822a\u6570\u636e\u7f16\u8f91\u5668", None))
        self.OpenDB.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u673a\u573a", None))
        self.ExportDB.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.SaveExcel.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u4e00\u4e2a\u673a\u573a\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"ID\uff1a", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u673a\u573a\u540d\u5b57(\u5927\u5199\u62fc\u97f3)\uff1a", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"ICAO\u4ee3\u7801\uff1a", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u7eac\u5ea6\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u7ecf\u5ea6\uff1a", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u673a\u573a\u6807\u9ad8(\u82f1\u5c3a)\uff1a", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"TA(\u82f1\u5c3a)\uff1a", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"TL(\u82f1\u5c3a)\uff1a", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u901f\u5ea6\u9650\u5236\uff1a", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u901f\u5ea6\u9650\u5236\u9ad8\u5ea6\uff1a", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"\u60c5\u62a5\u533a\u4ee3\u7801\uff1a", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"\u8dd1\u9053\uff1a", None))
        self.SaveAirport.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u673a\u573a", None))
        self.SaveRunway.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u8dd1\u9053", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u5168\u90e8\u5b8c\u6210\u4ee5\u540e\u70b9\u51fb\u83dc\u5355-\u4fdd\u5b58\uff0c\u7136\u540e\u6b64\u7a0b\u5e8f\u540c\u76ee\u5f55\u4e0b\u5c31\u4f1a\u51fa\u73b0Result.xls\uff0c\u7528Navicat\u5bfc\u5165\u5373\u53ef", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u8dd1\u9053ID\uff1a", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u5bf9\u5e94\u7684\u673a\u573aID\uff1a", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u8dd1\u9053\u7f16\u53f7\uff1a", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u8dd1\u9053\u771f\u822a\u5411\uff1a", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u8dd1\u9053\u957f\u5ea6\uff1a", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"\u8dd1\u9053\u5bbd\u5ea6\uff1a", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"\u8dd1\u9053\u9053\u9762\uff1a", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"\u8dd1\u9053\u7eac\u5ea6\uff1a", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"\u8dd1\u9053\u7ecf\u5ea6\uff1a", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"\u8dd1\u9053\u6807\u9ad8\uff1a", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"\u76f2\u964dID\uff1a", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"\u76f2\u964d\u9891\u7387\uff1a", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u6ed1\u89d2\uff1a", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"\u76f2\u964d\u7eac\u5ea6\uff1a", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"\u76f2\u964d\u7ecf\u5ea6\uff1a", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"\u76f2\u964d\u7c7b\u578b\uff1a", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"\u76f2\u964d\u4ee3\u7801\uff1a", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"\u822a\u5411\u9053\u65b9\u5411\uff1a", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"\u7a7f\u8d8a\u8dd1\u9053\u5165\u53e3\u9ad8\uff1a", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"\u662f\u5426\u6709\u6d4b\u8ddd\u53f0\uff1a", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"\u6807\u9ad8\uff1a", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u4f7f\u7528\u8bf4\u660e\uff1a\u4fee\u6539\u673a\u573a\u8bf7\u5148\u9009\u62e9\u4e00\u4e2a\u673a\u573a\uff0c\u7136\u540e\u5728\u539f\u6709\u7684\u57fa\u7840\u4e0a\u4fee\u6539\uff0c\u975e\u5fc5\u8981\u4e0d\u8981\u6539ID\uff0c\u4e0d\u7136\u53ef\u80fd\u5728\u5bfc\u5165\u7684\u65f6\u5019\u6ca1\u529e\u6cd5\u8986\u76d6\uff0c\u65b0\u5efa\u4e5f\u662f\u4e00\u6837\u76f4\u63a5\u586b\u5c31\u884c\uff0c\u586b\u5b8c\u70b9\u4fdd\u5b58\u4fee\u6539\u3002", None))
        self.ILSDME.setText("")
        self.AirportSearchButton.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2\u673a\u573a", None))
        self.SaveILS.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u76f2\u964d\u4fe1\u606f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u673a\u573a", None))
        self.WPSearchButton.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2\u822a\u70b9", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u8bc6\u522b\u7801\uff1a", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"ID\uff1a", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u60c5\u62a5\u533a\uff1a", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Collocated\uff1a", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"\u540d\u5b57\uff1a", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"\u7eac\u5ea6\uff1a", None))
        self.label_95.setText(QCoreApplication.translate("MainWindow", u"\u7ecf\u5ea6\uff1a", None))
        self.label_96.setText(QCoreApplication.translate("MainWindow", u"\u5bf9\u5e94\u5bfc\u822a\u8bbe\u65bdID\uff1a", None))
        self.WPSave.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u822a\u70b9", None))
        self.TMAAPSearchButton.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2\u673a\u573a", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"\u8fdb\u79bb\u573a\u5217\u8868\uff1a", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u673a\u573a\uff1a", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"\u822a\u6bb5\u5217\u8868\uff1a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u8fdb\u79bb\u573a", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u83dc\u5355", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
    # retranslateUi

